eureka:
  instance:
    prefer-ip-address: true
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
  client:
    fetch-registry: true
    register-with-eureka: true
okta:
  oauth2:
    issuer: https://dev-31013731.okta.com/oauth2/default
    audience: api://default